// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


var $$AudioNode = /* module */[];

var $$AudioParam = /* module */[];

var AudioSourceNode = /* module */[];

var $$OscillatorNode = /* module */[];

function make(options) {
  return new window.AudioContext(options);
}

function start(prim, prim$1) {
  prim.start(prim$1);
  return /* () */0;
}

function stop(prim, prim$1) {
  prim.stop(prim$1);
  return /* () */0;
}

function frequency(prim) {
  return prim.frequency;
}

function setValueAtTime(prim, prim$1, prim$2) {
  prim.setValueAtTime(prim$1, prim$2);
  return /* () */0;
}

exports.$$AudioNode = $$AudioNode;
exports.$$AudioParam = $$AudioParam;
exports.AudioSourceNode = AudioSourceNode;
exports.$$OscillatorNode = $$OscillatorNode;
exports.make = make;
exports.start = start;
exports.stop = stop;
exports.frequency = frequency;
exports.setValueAtTime = setValueAtTime;
/* No side effect */
