// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


function Delay(Props) {
  Props.delay;
  Props.duration;
  Props.clock;
  return null;
}

var make = Delay;

exports.make = make;
/* No side effect */
