// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Note$ReactHooksTemplate = require("./Note.bs.js");
var TempoProvider$ReactHooksTemplate = require("./TempoProvider.bs.js");

function Example(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* isPlaying */!state[/* isPlaying */0]];
        }), /* record */[/* isPlaying */false]);
  var dispatch = match[1];
  var match$1 = match[0][/* isPlaying */0];
  return React.createElement(TempoProvider$ReactHooksTemplate.make, TempoProvider$ReactHooksTemplate.makeProps(/* record */[/* tempo */120], null, /* () */0), React.createElement("div", undefined, "Muzik"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* TogglePlay */0);
                    })
                }, "Play/Stop"), match$1 ? React.createElement(React.Fragment, undefined, React.createElement(Note$ReactHooksTemplate.make, {
                        freq: /* Note */Block.__(1, [/* a3 */21682]),
                        duration: /* Quarter */2
                      }), React.createElement(Note$ReactHooksTemplate.make, {
                        freq: /* Note */Block.__(1, [/* h3 */23243]),
                        duration: /* Quarter */2,
                        delay: /* Quarter */2
                      }), React.createElement(Note$ReactHooksTemplate.make, {
                        freq: /* Note */Block.__(1, [/* c4 */22129]),
                        duration: /* Quarter */2,
                        delay: /* Quarter */2
                      }), React.createElement(Note$ReactHooksTemplate.make, {
                        freq: /* Note */Block.__(1, [/* c3 */22128]),
                        duration: /* Quarter */2,
                        delay: /* Quarter */2
                      }), React.createElement(Note$ReactHooksTemplate.make, {
                        freq: /* Note */Block.__(1, [/* e3 */22574]),
                        duration: /* Quarter */2,
                        delay: /* Quarter */2
                      })) : null);
}

var make = Example;

exports.make = make;
/* react Not a pure module */
