// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Sound$ReactHooksTemplate = require("./Sound.bs.js");

function Example(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* isPlaying */!state[/* isPlaying */0]];
        }), /* record */[/* isPlaying */false]);
  var dispatch = match[1];
  var match$1 = match[0][/* isPlaying */0];
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, "Muzik"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* TogglePlay */0);
                    })
                }), match$1 ? React.createElement(Sound$ReactHooksTemplate.make, { }) : null);
}

var make = Example;

exports.make = make;
/* react Not a pure module */
