// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


function frequencyFromNote(note) {
  if (note >= 22574) {
    if (note >= 23020) {
      if (note >= 23243) {
        return 246.94;
      } else {
        return 196.00;
      }
    } else if (note >= 22797) {
      return 174.61;
    } else {
      return 164.81;
    }
  } else if (note >= 22129) {
    if (note >= 22351) {
      return 146.83;
    } else {
      return 261.63;
    }
  } else if (note >= 22128) {
    return 130.81;
  } else {
    return 220.00;
  }
}

exports.frequencyFromNote = frequencyFromNote;
/* No side effect */
