// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Audio$ReactHooksTemplate = require("./Audio.bs.js");

function Sound(Props) {
  React.useEffect((function () {
          var audioContext = Audio$ReactHooksTemplate.make(undefined);
          var oscillator = new window.OscillatorNode(audioContext);
          var dest = audioContext.destination;
          var amp = new window.GainNode(audioContext);
          oscillator.connect(amp).connect(dest);
          var currentTime = audioContext.currentTime;
          Audio$ReactHooksTemplate.setValue(Audio$ReactHooksTemplate.freq(oscillator), 330, currentTime + 3.5);
          Audio$ReactHooksTemplate.start(oscillator, 0);
          return (function (param) {
                    return Audio$ReactHooksTemplate.stop(oscillator, 0);
                  });
        }));
  return null;
}

var make = Sound;

exports.make = make;
/* react Not a pure module */
