// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var tempoContext = React.createContext(/* record */[/* tempo */120]);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = tempoContext.Provider;

exports.tempoContext = tempoContext;
exports.makeProps = makeProps;
exports.make = make;
/* tempoContext Not a pure module */
